#!/bin/bash

# Supabase Project Setup Script
# Purpose: Automates the creation of a new Supabase project for EduQuest admin dashboard
# Usage: ./supabase-project-setup.sh [project-name] [database-password] [region]

set -e  # Exit on any error

# Source shared utilities
source "$(dirname "$0")/../lib/logging.sh"
source "$(dirname "$0")/../lib/retry-utils.sh"

# Configuration
DEFAULT_PROJECT_NAME="eduquest-admin"
DEFAULT_REGION="us-east-1"
ORGANIZATION_NAME="eduquest"
PASSWORD_FILE=".supabase_db_password"

# Function to display usage
usage() {
    echo "Usage: $0 [project-name] [database-password] [region]"
    echo "  project-name:    Supabase project name (default: $DEFAULT_PROJECT_NAME)"
    echo "  database-password: Database password (leave empty for auto-generation)"
    echo "  region:         Deployment region (default: $DEFAULT_REGION)"
    exit 1
}

# Function to validate input
validate_inputs() {
    local project_name="$1"
    local db_password="$2"
    local region="$3"

    # Validate project name
    if [[ ! "$project_name" =~ ^[a-z][a-z0-9-]{2,63}$ ]]; then
        log_error "Invalid project name: '$project_name'"
        echo "Project name must:"
        echo "  - Start with a letter"
        echo "  - Contain only lowercase letters, numbers, and hyphens"
        echo "  - Be 3-64 characters long"
        exit 1
    fi

    # Validate region
    valid_regions=("us-east-1" "us-west-1" "eu-west-1" "ap-southeast-1")
    local region_found=false
    for r in "${valid_regions[@]}"; do
        if [[ "$r" == "$region" ]]; then
            region_found=true
            break
        fi
    done

    if ! $region_found; then
        log_error "Invalid region: '$region'"
        echo "Valid regions are: ${valid_regions[*]}"
        exit 1
    fi

    # Check if Supabase CLI is installed
    if ! command -v supabase &> /dev/null; then
        log_error "Supabase CLI is not installed"
        echo "Please install from: https://supabase.com/docs/guides/cli/getting-started"
        exit 1
    fi

    # Check if user is authenticated
    if ! supabase auth list &> /dev/null; then
        log_error "Not authenticated with Supabase CLI"
        echo "Please run: supabase login"
        exit 1
    fi
}

# Function to generate a secure password
generate_password() {
    openssl rand -base64 32 | tr -d '+/' | cut -c1-25
}

# Function to create Supabase project
create_project() {
    local project_name="$1"
    local db_password="$2"
    local region="$3"
    local start_time
    start_time=$(date +%s)

    log_info "Creating Supabase project: $project_name"

    # Create project using CLI (password passed via environment variable to avoid /proc exposure)
    if SUPABASE_DB_PASSWORD="$db_password" supabase projects create "$project_name" \
        --region "$region" \
        --org "$ORGANIZATION_NAME" 2>&1 | grep -q "Created"; then
        log_info "Project creation initiated successfully"
    else
        log_error "Failed to create project"
        exit 1
    fi

    # Wait for project to be ready using retry utility
    log_info "Waiting for project to be ready..."
    if wait_for_project_creation "$project_name"; then
        local end_time
        end_time=$(date +%s)
        local duration=$((end_time - start_time))
        log_info "Project created successfully in ${duration}s"

        # Store project reference
        PROJECT_REF=$(supabase projects list | grep "$project_name" | awk '{print $1}')
        echo "$PROJECT_REF" > .supabase_project_ref

        return 0
    else
        log_error "Project creation timed out"
        exit 1
    fi
}

# Function to verify project creation
verify_project() {
    local project_name="$1"

    log_info "Verifying project creation..."

    # Check if project exists in list
    if ! supabase projects list 2>/dev/null | grep -q "$project_name"; then
        log_error "Project not found in list"
        exit 1
    fi

    # Check project status
    local list_output
    if ! list_output=$(supabase projects list 2>/dev/null); then
        log_error "Failed to list projects"
        exit 1
    fi

    local status
    status=$(echo "$list_output" | grep "$project_name" | awk '{print $2}')
    if [[ "$status" != "ACTIVE" ]]; then
        log_error "Project is not active (status: $status)"
        exit 1
    fi

    log_success "Project verification successful"
}

# Function to store configuration
save_config() {
    local project_name="$1"
    local project_ref="$2"

    # Create config file
    cat > ".supabase_config" << EOF
# Supabase Configuration
# Generated by supabase-project-setup.sh

PROJECT_NAME=$project_name
PROJECT_REF=$project_ref
REGION=$DEFAULT_REGION
ORGANIZATION=$ORGANIZATION_NAME

# Connection strings
SUPABASE_URL=https://$project_ref.supabase.co
EOF

    log_info "Configuration saved to .supabase_config"
}

# Main execution
main() {
    # Parse arguments
    local project_name="${1:-$DEFAULT_PROJECT_NAME}"
    local db_password="$2"
    local region="${3:-$DEFAULT_REGION}"

    log_info "Starting Supabase project setup..."
    log_info "Project: $project_name"
    log_info "Region: $region"

    # Validate inputs
    validate_inputs "$project_name" "$db_password" "$region"

    # Generate password if not provided
    if [[ -z "$db_password" ]]; then
        db_password=$(generate_password)
        # Save password to secure file instead of logging
        echo "$db_password" > "$PASSWORD_FILE"
        chmod 600 "$PASSWORD_FILE"
        log_warn "Database password generated and saved to $PASSWORD_FILE"
        log_warn "Please save this password securely and delete the file!"
    fi

    # Create project
    create_project "$project_name" "$db_password" "$region"

    # Verify project
    verify_project "$project_name"

    # Save configuration
    PROJECT_REF=$(cat .supabase_project_ref)
    save_config "$project_name" "$PROJECT_REF"

    # Display success message with next steps
    echo
    log_success "Setup completed successfully!"
    echo
    echo "Next Steps:"
    echo "1. Project reference: $PROJECT_REF"
    if [[ -f "$PASSWORD_FILE" ]]; then
        echo "2. Database password: saved in $PASSWORD_FILE (delete after saving securely)"
    fi
    echo "3. URL: https://$PROJECT_REF.supabase.co"
    echo
    echo "To link your local project:"
    echo "  supabase link --project-ref $PROJECT_REF"
    echo
    echo "To verify connection:"
    echo "  supabase status"
    echo
}

# Run main function with all arguments
main "$@"